// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runUpse
int runUpse(const char* input, const char* format, const char* module, const char* note, const char* property, const char* omega, const char* lambda, const char* type);
RcppExport SEXP _UltraPseR_runUpse(SEXP inputSEXP, SEXP formatSEXP, SEXP moduleSEXP, SEXP noteSEXP, SEXP propertySEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const char* >::type format(formatSEXP);
    Rcpp::traits::input_parameter< const char* >::type module(moduleSEXP);
    Rcpp::traits::input_parameter< const char* >::type note(noteSEXP);
    Rcpp::traits::input_parameter< const char* >::type property(propertySEXP);
    Rcpp::traits::input_parameter< const char* >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const char* >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const char* >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(runUpse(input, format, module, note, property, omega, lambda, type));
    return rcpp_result_gen;
END_RCPP
}
// available_property
int available_property(const char* note);
RcppExport SEXP _UltraPseR_available_property(SEXP noteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type note(noteSEXP);
    rcpp_result_gen = Rcpp::wrap(available_property(note));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UltraPseR_runUpse", (DL_FUNC) &_UltraPseR_runUpse, 8},
    {"_UltraPseR_available_property", (DL_FUNC) &_UltraPseR_available_property, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_UltraPseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
